# Generated by Django 3.0.7 on 2020-06-13 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, max_length=2047)),
                ('created', models.DateTimeField(blank=True, default=None, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_set', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
                ('super_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SignableTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('start_signing', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_signing', models.DateTimeField(blank=True, default=None, null=True)),
                ('capacity', models.IntegerField()),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('sponsor_price', models.IntegerField(blank=True, default=None, null=True)),
            ],
            bases=('tasks.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='task_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.TaskState'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
