# Generated by Django 3.0.7 on 2020-06-13 17:09

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signabletask',
            name='image',
            field=stdimage.models.StdImageField(default='logo.png', upload_to='images'),
            preserve_default=False,
        ),
    ]
