# Generated by Django 3.0.7 on 2020-07-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200704_0749'),
        ('tasks', '0004_auto_20200613_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.SignableTask')),
            ],
        ),
        migrations.AddField(
            model_name='signabletask',
            name='applications',
            field=models.ManyToManyField(through='tasks.Application', to='accounts.Profile'),
        ),
    ]
