# Generated by Django 3.0.7 on 2020-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200704_0749'),
        ('tasks', '0007_auto_20200716_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('NP', 'Nezaplaceno'), ('PA', 'Zaplaceno'), ('SU', 'Zažádáno o zrušení')], default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='signabletask',
            name='applications',
            field=models.ManyToManyField(related_name='applications', through='tasks.Application', to='accounts.Profile'),
        ),
    ]
