# Generated by Django 3.0.7 on 2020-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200716_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('NP', 'Nezaplaceno'), ('PA', 'Zaplaceno'), ('SU', 'Zažádáno o zrušení')], default='NP', max_length=2, verbose_name='Stav'),
        ),
    ]
